/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSociosRouteImport } from './routes/app.socios'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppMovementsRouteImport } from './routes/app.movements'
import { Route as AppLocationsRouteImport } from './routes/app.locations'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCultivoRouteImport } from './routes/app.cultivo'
import { Route as AppCatalogRouteImport } from './routes/app.catalog'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAlertasRouteImport } from './routes/app.alertas'
import { Route as AppAiInsightsRouteImport } from './routes/app.ai-insights'
import { Route as AppCultivoVpdRouteImport } from './routes/app.cultivo.vpd'
import { Route as AppCultivoSalasRouteImport } from './routes/app.cultivo.salas'
import { Route as AppCultivoResumenRouteImport } from './routes/app.cultivo.resumen'
import { Route as AppCultivoPlantasRouteImport } from './routes/app.cultivo.plantas'
import { Route as AppCultivoMedicionesRouteImport } from './routes/app.cultivo.mediciones'
import { Route as AppCultivoMadresRouteImport } from './routes/app.cultivo.madres'
import { Route as AppCultivoGeneticasRouteImport } from './routes/app.cultivo.geneticas'
import { Route as AppCultivoCamillasRouteImport } from './routes/app.cultivo.camillas'
import { Route as AppCultivoCalendarioRouteImport } from './routes/app.cultivo.calendario'
import { Route as AppCultivoAmbienteRouteImport } from './routes/app.cultivo.ambiente'
import { Route as AppCultivoSalasNuevaRouteImport } from './routes/app.cultivo.salas.nueva'
import { Route as AppCultivoSalasIdRouteImport } from './routes/app.cultivo.salas.$id'
import { Route as AppCultivoPlantasNuevaRouteImport } from './routes/app.cultivo.plantas.nueva'
import { Route as AppCultivoGeneticasNuevaRouteImport } from './routes/app.cultivo.geneticas.nueva'
import { Route as AppCultivoGeneticasIdRouteImport } from './routes/app.cultivo.geneticas.$id'
import { Route as AppCultivoCamillasNuevaRouteImport } from './routes/app.cultivo.camillas.nueva'
import { Route as AppCultivoCamillasIdRouteImport } from './routes/app.cultivo.camillas.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSociosRoute = AppSociosRouteImport.update({
  id: '/socios',
  path: '/socios',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppMovementsRoute = AppMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppRoute,
} as any)
const AppLocationsRoute = AppLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCultivoRoute = AppCultivoRouteImport.update({
  id: '/cultivo',
  path: '/cultivo',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogRoute = AppCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppAiInsightsRoute = AppAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => AppRoute,
} as any)
const AppCultivoVpdRoute = AppCultivoVpdRouteImport.update({
  id: '/vpd',
  path: '/vpd',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoSalasRoute = AppCultivoSalasRouteImport.update({
  id: '/salas',
  path: '/salas',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoResumenRoute = AppCultivoResumenRouteImport.update({
  id: '/resumen',
  path: '/resumen',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoPlantasRoute = AppCultivoPlantasRouteImport.update({
  id: '/plantas',
  path: '/plantas',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoMedicionesRoute = AppCultivoMedicionesRouteImport.update({
  id: '/mediciones',
  path: '/mediciones',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoMadresRoute = AppCultivoMadresRouteImport.update({
  id: '/madres',
  path: '/madres',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoGeneticasRoute = AppCultivoGeneticasRouteImport.update({
  id: '/geneticas',
  path: '/geneticas',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoCamillasRoute = AppCultivoCamillasRouteImport.update({
  id: '/camillas',
  path: '/camillas',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoCalendarioRoute = AppCultivoCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoAmbienteRoute = AppCultivoAmbienteRouteImport.update({
  id: '/ambiente',
  path: '/ambiente',
  getParentRoute: () => AppCultivoRoute,
} as any)
const AppCultivoSalasNuevaRoute = AppCultivoSalasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppCultivoSalasRoute,
} as any)
const AppCultivoSalasIdRoute = AppCultivoSalasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCultivoSalasRoute,
} as any)
const AppCultivoPlantasNuevaRoute = AppCultivoPlantasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppCultivoPlantasRoute,
} as any)
const AppCultivoGeneticasNuevaRoute =
  AppCultivoGeneticasNuevaRouteImport.update({
    id: '/nueva',
    path: '/nueva',
    getParentRoute: () => AppCultivoGeneticasRoute,
  } as any)
const AppCultivoGeneticasIdRoute = AppCultivoGeneticasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCultivoGeneticasRoute,
} as any)
const AppCultivoCamillasNuevaRoute = AppCultivoCamillasNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AppCultivoCamillasRoute,
} as any)
const AppCultivoCamillasIdRoute = AppCultivoCamillasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCultivoCamillasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/cultivo': typeof AppCultivoRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/socios': typeof AppSociosRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/cultivo/ambiente': typeof AppCultivoAmbienteRoute
  '/app/cultivo/calendario': typeof AppCultivoCalendarioRoute
  '/app/cultivo/camillas': typeof AppCultivoCamillasRouteWithChildren
  '/app/cultivo/geneticas': typeof AppCultivoGeneticasRouteWithChildren
  '/app/cultivo/madres': typeof AppCultivoMadresRoute
  '/app/cultivo/mediciones': typeof AppCultivoMedicionesRoute
  '/app/cultivo/plantas': typeof AppCultivoPlantasRouteWithChildren
  '/app/cultivo/resumen': typeof AppCultivoResumenRoute
  '/app/cultivo/salas': typeof AppCultivoSalasRouteWithChildren
  '/app/cultivo/vpd': typeof AppCultivoVpdRoute
  '/app/cultivo/camillas/$id': typeof AppCultivoCamillasIdRoute
  '/app/cultivo/camillas/nueva': typeof AppCultivoCamillasNuevaRoute
  '/app/cultivo/geneticas/$id': typeof AppCultivoGeneticasIdRoute
  '/app/cultivo/geneticas/nueva': typeof AppCultivoGeneticasNuevaRoute
  '/app/cultivo/plantas/nueva': typeof AppCultivoPlantasNuevaRoute
  '/app/cultivo/salas/$id': typeof AppCultivoSalasIdRoute
  '/app/cultivo/salas/nueva': typeof AppCultivoSalasNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/cultivo': typeof AppCultivoRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/socios': typeof AppSociosRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/cultivo/ambiente': typeof AppCultivoAmbienteRoute
  '/app/cultivo/calendario': typeof AppCultivoCalendarioRoute
  '/app/cultivo/camillas': typeof AppCultivoCamillasRouteWithChildren
  '/app/cultivo/geneticas': typeof AppCultivoGeneticasRouteWithChildren
  '/app/cultivo/madres': typeof AppCultivoMadresRoute
  '/app/cultivo/mediciones': typeof AppCultivoMedicionesRoute
  '/app/cultivo/plantas': typeof AppCultivoPlantasRouteWithChildren
  '/app/cultivo/resumen': typeof AppCultivoResumenRoute
  '/app/cultivo/salas': typeof AppCultivoSalasRouteWithChildren
  '/app/cultivo/vpd': typeof AppCultivoVpdRoute
  '/app/cultivo/camillas/$id': typeof AppCultivoCamillasIdRoute
  '/app/cultivo/camillas/nueva': typeof AppCultivoCamillasNuevaRoute
  '/app/cultivo/geneticas/$id': typeof AppCultivoGeneticasIdRoute
  '/app/cultivo/geneticas/nueva': typeof AppCultivoGeneticasNuevaRoute
  '/app/cultivo/plantas/nueva': typeof AppCultivoPlantasNuevaRoute
  '/app/cultivo/salas/$id': typeof AppCultivoSalasIdRoute
  '/app/cultivo/salas/nueva': typeof AppCultivoSalasNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/ai-insights': typeof AppAiInsightsRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/catalog': typeof AppCatalogRoute
  '/app/cultivo': typeof AppCultivoRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/help': typeof AppHelpRoute
  '/app/locations': typeof AppLocationsRoute
  '/app/movements': typeof AppMovementsRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/socios': typeof AppSociosRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/cultivo/ambiente': typeof AppCultivoAmbienteRoute
  '/app/cultivo/calendario': typeof AppCultivoCalendarioRoute
  '/app/cultivo/camillas': typeof AppCultivoCamillasRouteWithChildren
  '/app/cultivo/geneticas': typeof AppCultivoGeneticasRouteWithChildren
  '/app/cultivo/madres': typeof AppCultivoMadresRoute
  '/app/cultivo/mediciones': typeof AppCultivoMedicionesRoute
  '/app/cultivo/plantas': typeof AppCultivoPlantasRouteWithChildren
  '/app/cultivo/resumen': typeof AppCultivoResumenRoute
  '/app/cultivo/salas': typeof AppCultivoSalasRouteWithChildren
  '/app/cultivo/vpd': typeof AppCultivoVpdRoute
  '/app/cultivo/camillas/$id': typeof AppCultivoCamillasIdRoute
  '/app/cultivo/camillas/nueva': typeof AppCultivoCamillasNuevaRoute
  '/app/cultivo/geneticas/$id': typeof AppCultivoGeneticasIdRoute
  '/app/cultivo/geneticas/nueva': typeof AppCultivoGeneticasNuevaRoute
  '/app/cultivo/plantas/nueva': typeof AppCultivoPlantasNuevaRoute
  '/app/cultivo/salas/$id': typeof AppCultivoSalasIdRoute
  '/app/cultivo/salas/nueva': typeof AppCultivoSalasNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/ai-insights'
    | '/app/alertas'
    | '/app/analytics'
    | '/app/auditoria'
    | '/app/catalog'
    | '/app/cultivo'
    | '/app/dashboard'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/purchase-orders'
    | '/app/requests'
    | '/app/settings'
    | '/app/socios'
    | '/app/suppliers'
    | '/app/usuarios'
    | '/app/'
    | '/app/cultivo/ambiente'
    | '/app/cultivo/calendario'
    | '/app/cultivo/camillas'
    | '/app/cultivo/geneticas'
    | '/app/cultivo/madres'
    | '/app/cultivo/mediciones'
    | '/app/cultivo/plantas'
    | '/app/cultivo/resumen'
    | '/app/cultivo/salas'
    | '/app/cultivo/vpd'
    | '/app/cultivo/camillas/$id'
    | '/app/cultivo/camillas/nueva'
    | '/app/cultivo/geneticas/$id'
    | '/app/cultivo/geneticas/nueva'
    | '/app/cultivo/plantas/nueva'
    | '/app/cultivo/salas/$id'
    | '/app/cultivo/salas/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/ai-insights'
    | '/app/alertas'
    | '/app/analytics'
    | '/app/auditoria'
    | '/app/catalog'
    | '/app/cultivo'
    | '/app/dashboard'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/purchase-orders'
    | '/app/requests'
    | '/app/settings'
    | '/app/socios'
    | '/app/suppliers'
    | '/app/usuarios'
    | '/app'
    | '/app/cultivo/ambiente'
    | '/app/cultivo/calendario'
    | '/app/cultivo/camillas'
    | '/app/cultivo/geneticas'
    | '/app/cultivo/madres'
    | '/app/cultivo/mediciones'
    | '/app/cultivo/plantas'
    | '/app/cultivo/resumen'
    | '/app/cultivo/salas'
    | '/app/cultivo/vpd'
    | '/app/cultivo/camillas/$id'
    | '/app/cultivo/camillas/nueva'
    | '/app/cultivo/geneticas/$id'
    | '/app/cultivo/geneticas/nueva'
    | '/app/cultivo/plantas/nueva'
    | '/app/cultivo/salas/$id'
    | '/app/cultivo/salas/nueva'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/ai-insights'
    | '/app/alertas'
    | '/app/analytics'
    | '/app/auditoria'
    | '/app/catalog'
    | '/app/cultivo'
    | '/app/dashboard'
    | '/app/help'
    | '/app/locations'
    | '/app/movements'
    | '/app/purchase-orders'
    | '/app/requests'
    | '/app/settings'
    | '/app/socios'
    | '/app/suppliers'
    | '/app/usuarios'
    | '/app/'
    | '/app/cultivo/ambiente'
    | '/app/cultivo/calendario'
    | '/app/cultivo/camillas'
    | '/app/cultivo/geneticas'
    | '/app/cultivo/madres'
    | '/app/cultivo/mediciones'
    | '/app/cultivo/plantas'
    | '/app/cultivo/resumen'
    | '/app/cultivo/salas'
    | '/app/cultivo/vpd'
    | '/app/cultivo/camillas/$id'
    | '/app/cultivo/camillas/nueva'
    | '/app/cultivo/geneticas/$id'
    | '/app/cultivo/geneticas/nueva'
    | '/app/cultivo/plantas/nueva'
    | '/app/cultivo/salas/$id'
    | '/app/cultivo/salas/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/socios': {
      id: '/app/socios'
      path: '/socios'
      fullPath: '/app/socios'
      preLoaderRoute: typeof AppSociosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/movements': {
      id: '/app/movements'
      path: '/movements'
      fullPath: '/app/movements'
      preLoaderRoute: typeof AppMovementsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/locations': {
      id: '/app/locations'
      path: '/locations'
      fullPath: '/app/locations'
      preLoaderRoute: typeof AppLocationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cultivo': {
      id: '/app/cultivo'
      path: '/cultivo'
      fullPath: '/app/cultivo'
      preLoaderRoute: typeof AppCultivoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/catalog': {
      id: '/app/catalog'
      path: '/catalog'
      fullPath: '/app/catalog'
      preLoaderRoute: typeof AppCatalogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ai-insights': {
      id: '/app/ai-insights'
      path: '/ai-insights'
      fullPath: '/app/ai-insights'
      preLoaderRoute: typeof AppAiInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cultivo/vpd': {
      id: '/app/cultivo/vpd'
      path: '/vpd'
      fullPath: '/app/cultivo/vpd'
      preLoaderRoute: typeof AppCultivoVpdRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/salas': {
      id: '/app/cultivo/salas'
      path: '/salas'
      fullPath: '/app/cultivo/salas'
      preLoaderRoute: typeof AppCultivoSalasRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/resumen': {
      id: '/app/cultivo/resumen'
      path: '/resumen'
      fullPath: '/app/cultivo/resumen'
      preLoaderRoute: typeof AppCultivoResumenRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/plantas': {
      id: '/app/cultivo/plantas'
      path: '/plantas'
      fullPath: '/app/cultivo/plantas'
      preLoaderRoute: typeof AppCultivoPlantasRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/mediciones': {
      id: '/app/cultivo/mediciones'
      path: '/mediciones'
      fullPath: '/app/cultivo/mediciones'
      preLoaderRoute: typeof AppCultivoMedicionesRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/madres': {
      id: '/app/cultivo/madres'
      path: '/madres'
      fullPath: '/app/cultivo/madres'
      preLoaderRoute: typeof AppCultivoMadresRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/geneticas': {
      id: '/app/cultivo/geneticas'
      path: '/geneticas'
      fullPath: '/app/cultivo/geneticas'
      preLoaderRoute: typeof AppCultivoGeneticasRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/camillas': {
      id: '/app/cultivo/camillas'
      path: '/camillas'
      fullPath: '/app/cultivo/camillas'
      preLoaderRoute: typeof AppCultivoCamillasRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/calendario': {
      id: '/app/cultivo/calendario'
      path: '/calendario'
      fullPath: '/app/cultivo/calendario'
      preLoaderRoute: typeof AppCultivoCalendarioRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/ambiente': {
      id: '/app/cultivo/ambiente'
      path: '/ambiente'
      fullPath: '/app/cultivo/ambiente'
      preLoaderRoute: typeof AppCultivoAmbienteRouteImport
      parentRoute: typeof AppCultivoRoute
    }
    '/app/cultivo/salas/nueva': {
      id: '/app/cultivo/salas/nueva'
      path: '/nueva'
      fullPath: '/app/cultivo/salas/nueva'
      preLoaderRoute: typeof AppCultivoSalasNuevaRouteImport
      parentRoute: typeof AppCultivoSalasRoute
    }
    '/app/cultivo/salas/$id': {
      id: '/app/cultivo/salas/$id'
      path: '/$id'
      fullPath: '/app/cultivo/salas/$id'
      preLoaderRoute: typeof AppCultivoSalasIdRouteImport
      parentRoute: typeof AppCultivoSalasRoute
    }
    '/app/cultivo/plantas/nueva': {
      id: '/app/cultivo/plantas/nueva'
      path: '/nueva'
      fullPath: '/app/cultivo/plantas/nueva'
      preLoaderRoute: typeof AppCultivoPlantasNuevaRouteImport
      parentRoute: typeof AppCultivoPlantasRoute
    }
    '/app/cultivo/geneticas/nueva': {
      id: '/app/cultivo/geneticas/nueva'
      path: '/nueva'
      fullPath: '/app/cultivo/geneticas/nueva'
      preLoaderRoute: typeof AppCultivoGeneticasNuevaRouteImport
      parentRoute: typeof AppCultivoGeneticasRoute
    }
    '/app/cultivo/geneticas/$id': {
      id: '/app/cultivo/geneticas/$id'
      path: '/$id'
      fullPath: '/app/cultivo/geneticas/$id'
      preLoaderRoute: typeof AppCultivoGeneticasIdRouteImport
      parentRoute: typeof AppCultivoGeneticasRoute
    }
    '/app/cultivo/camillas/nueva': {
      id: '/app/cultivo/camillas/nueva'
      path: '/nueva'
      fullPath: '/app/cultivo/camillas/nueva'
      preLoaderRoute: typeof AppCultivoCamillasNuevaRouteImport
      parentRoute: typeof AppCultivoCamillasRoute
    }
    '/app/cultivo/camillas/$id': {
      id: '/app/cultivo/camillas/$id'
      path: '/$id'
      fullPath: '/app/cultivo/camillas/$id'
      preLoaderRoute: typeof AppCultivoCamillasIdRouteImport
      parentRoute: typeof AppCultivoCamillasRoute
    }
  }
}

interface AppCultivoCamillasRouteChildren {
  AppCultivoCamillasIdRoute: typeof AppCultivoCamillasIdRoute
  AppCultivoCamillasNuevaRoute: typeof AppCultivoCamillasNuevaRoute
}

const AppCultivoCamillasRouteChildren: AppCultivoCamillasRouteChildren = {
  AppCultivoCamillasIdRoute: AppCultivoCamillasIdRoute,
  AppCultivoCamillasNuevaRoute: AppCultivoCamillasNuevaRoute,
}

const AppCultivoCamillasRouteWithChildren =
  AppCultivoCamillasRoute._addFileChildren(AppCultivoCamillasRouteChildren)

interface AppCultivoGeneticasRouteChildren {
  AppCultivoGeneticasIdRoute: typeof AppCultivoGeneticasIdRoute
  AppCultivoGeneticasNuevaRoute: typeof AppCultivoGeneticasNuevaRoute
}

const AppCultivoGeneticasRouteChildren: AppCultivoGeneticasRouteChildren = {
  AppCultivoGeneticasIdRoute: AppCultivoGeneticasIdRoute,
  AppCultivoGeneticasNuevaRoute: AppCultivoGeneticasNuevaRoute,
}

const AppCultivoGeneticasRouteWithChildren =
  AppCultivoGeneticasRoute._addFileChildren(AppCultivoGeneticasRouteChildren)

interface AppCultivoPlantasRouteChildren {
  AppCultivoPlantasNuevaRoute: typeof AppCultivoPlantasNuevaRoute
}

const AppCultivoPlantasRouteChildren: AppCultivoPlantasRouteChildren = {
  AppCultivoPlantasNuevaRoute: AppCultivoPlantasNuevaRoute,
}

const AppCultivoPlantasRouteWithChildren =
  AppCultivoPlantasRoute._addFileChildren(AppCultivoPlantasRouteChildren)

interface AppCultivoSalasRouteChildren {
  AppCultivoSalasIdRoute: typeof AppCultivoSalasIdRoute
  AppCultivoSalasNuevaRoute: typeof AppCultivoSalasNuevaRoute
}

const AppCultivoSalasRouteChildren: AppCultivoSalasRouteChildren = {
  AppCultivoSalasIdRoute: AppCultivoSalasIdRoute,
  AppCultivoSalasNuevaRoute: AppCultivoSalasNuevaRoute,
}

const AppCultivoSalasRouteWithChildren = AppCultivoSalasRoute._addFileChildren(
  AppCultivoSalasRouteChildren,
)

interface AppCultivoRouteChildren {
  AppCultivoAmbienteRoute: typeof AppCultivoAmbienteRoute
  AppCultivoCalendarioRoute: typeof AppCultivoCalendarioRoute
  AppCultivoCamillasRoute: typeof AppCultivoCamillasRouteWithChildren
  AppCultivoGeneticasRoute: typeof AppCultivoGeneticasRouteWithChildren
  AppCultivoMadresRoute: typeof AppCultivoMadresRoute
  AppCultivoMedicionesRoute: typeof AppCultivoMedicionesRoute
  AppCultivoPlantasRoute: typeof AppCultivoPlantasRouteWithChildren
  AppCultivoResumenRoute: typeof AppCultivoResumenRoute
  AppCultivoSalasRoute: typeof AppCultivoSalasRouteWithChildren
  AppCultivoVpdRoute: typeof AppCultivoVpdRoute
}

const AppCultivoRouteChildren: AppCultivoRouteChildren = {
  AppCultivoAmbienteRoute: AppCultivoAmbienteRoute,
  AppCultivoCalendarioRoute: AppCultivoCalendarioRoute,
  AppCultivoCamillasRoute: AppCultivoCamillasRouteWithChildren,
  AppCultivoGeneticasRoute: AppCultivoGeneticasRouteWithChildren,
  AppCultivoMadresRoute: AppCultivoMadresRoute,
  AppCultivoMedicionesRoute: AppCultivoMedicionesRoute,
  AppCultivoPlantasRoute: AppCultivoPlantasRouteWithChildren,
  AppCultivoResumenRoute: AppCultivoResumenRoute,
  AppCultivoSalasRoute: AppCultivoSalasRouteWithChildren,
  AppCultivoVpdRoute: AppCultivoVpdRoute,
}

const AppCultivoRouteWithChildren = AppCultivoRoute._addFileChildren(
  AppCultivoRouteChildren,
)

interface AppRouteChildren {
  AppAiInsightsRoute: typeof AppAiInsightsRoute
  AppAlertasRoute: typeof AppAlertasRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppCatalogRoute: typeof AppCatalogRoute
  AppCultivoRoute: typeof AppCultivoRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLocationsRoute: typeof AppLocationsRoute
  AppMovementsRoute: typeof AppMovementsRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSociosRoute: typeof AppSociosRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiInsightsRoute: AppAiInsightsRoute,
  AppAlertasRoute: AppAlertasRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppCatalogRoute: AppCatalogRoute,
  AppCultivoRoute: AppCultivoRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppHelpRoute: AppHelpRoute,
  AppLocationsRoute: AppLocationsRoute,
  AppMovementsRoute: AppMovementsRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSociosRoute: AppSociosRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
